### ISSUE TITLE
[FEA]: build_container.sh option to select docker instead of podman

### ISSUE THREAD

**Issue by eborin** [discovery-unicamp/dasf-core#8]
By default, build_container.sh selects podman instead of docker in case podman is installed on the system. It would be useful to have a flag that forces the script to use docker even if podman is present.

**Comment by eborin** [comment]
The same should be done for the start_jupyter_server.sh script.

**Comment by jcfaracco** [comment]
@eborin now you can pass `CONTAINER_CMD=docker` as an env variable.

E.g.:

```
$ CONTAINER_CMD=docker ./build_container.sh
```
